openapi: 3.0.3
info:
  title: The SpatioTemporal Asset Catalog API - CollectionCollection
  description: The specification for a set of collections, e.g. returned by a search.
  version: v1.0.0
paths: {}
components:
  schemas:
    collectionCollection:
      description: >-
        A iist of collections with related information, e.g. returned by a search.
      type: object
      required:
        - collections
        - type
      properties:
        collections:
          type: array
          items:
            $ref: "../../core/commons.yaml#/components/schemas/collection"
        links:
          type: array
          description: >-
            An array of links. Can be used for pagination, e.g. by providing a link
            with the `next` relation type.
          items:
            $ref: "../../core/commons.yaml#/components/schemas/link"
          example:
            - rel: next
              type: application/geo+json
              href: >-
                http://api.cool-sat.com/collections?page=2
        numberMatched:
          type: integer
          minimum: 0
        numberReturned:
          type: integer
          minimum: 0
